### ISSUE TITLE
 some issues with grid map 

### ISSUE THREAD

**Issue by feng1126** [LiJiangnanBit/path_optimizer#5]
Hi, i have tested your code with ros kinetic ,but I found some question when I run the demo, the log like this 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0513 08:58:02.135192 11617 tension_smoother.cpp:84] Tension smoother succeeded!
I0513 08:58:02.135460 11617 reference_path_impl.cpp:417] Reference states are built from spline.
[1]    11617 segmentation fault (core dumped)  rosrun path_optimizer path_optimizer_benchmark
Then I  found some problem with the code :       
   auto clearance_0 = getClearanceWithDirectionStrict(c0, map);
I wonder if i have some problem with my ros package grip map?

**Comment by LiJiangnanBit** [comment]
Hi, are you running the latest version of this program? I noticed in your log that the Tension smoother is used, but I set another smoother as default because Tension smoother behaves strangely sometimes. I'm not sure if this caused your problem.

Also, did you try
```
roslaunch path_optimizer demo
```
If Rviz displays your map correctly as below, grid_map package works fine.
![image](https://user-images.githubusercontent.com/23288471/81762394-151cc600-94ff-11ea-98a6-9c263585f407.png)
You can try this demo as instructed in the Readme file, and see if the same problem occurs.
Thanks for testing this package.:smile:

**Comment by feng1126** [comment]
Hi ,i also have tried  run roslaunch path_optimizer demo,the  log look like this 

[ INFO] [1589335964.906761698]: Setting goal: Frame:map, Position(63.693, -38.176, 0.000), Orientation(0.000, 0.000, -0.732, 0.681) = Angle: -1.642

get the goal.
------
Search time cost: 0.77 ms.
ref path length: 81.6211

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

I0513 10:12:44.964879 17481 angle_diff_smoother.cpp:192] Angle diff smoother succeeded!
I0513 10:12:44.965195 17481 reference_path_impl.cpp:417] Reference states are built from spline.
[path_optimizer_demo-1] process has died [pid 17481, exit code -11, cmd /home/feng/catkin_ws/devel/lib/path_optimizer/path_optimizer_demo --log_dir=. __name:=path_optimizer_demo __log:=/home/feng/.ros/log/c1e2d4f2-94bd-11ea-b4b0-005056c00001/path_optimizer_demo-1.log].
log file: /home/feng/.ros/log/c1e2d4f2-94bd-11ea-b4b0-005056c00001/path_optimizer_demo-1*.log

The question is remain. I also found some problem with the code :
auto clearance_0 = getClearanceWithDirectionStrict(c0, map);

I have change some config file and my code  is matser branch

**Comment by LiJiangnanBit** [comment]
Sorry, I wasn't able to reproduce the bug. It seems to be related to memory corruption.  

Did this problem occur when you use the default config? I wonder if this is due to the change of config.

It is likely that the bug exists in the function getClearanceWithDirectionStrict, I think I wrote pretty bad code in that function, and I'm thinking about rewrite it...but it has been working fine for me yet. Can you locate the exact line that killed the program?
Thanks.

**Comment by feng1126** [comment]
Everything works well after i reinstall the operate system, so i think it is my problem
 the code works well
