### ISSUE TITLE
demo.launch does't work 

### ISSUE THREAD

**Issue by k0suke-murakami** [LiJiangnanBit/path_optimizer#6]
Hi, thank you for sharing the amazing repo.
Here is what I found while trying to run your demo.launch

## Description
A trajectory isn't generated after following the guidance in readme.md.

## Code
commit: a95f0d06ec154ad79dfc87f12eff40c9e6db177b
Nothing has been modified including config file.

## Steps to reproduce 
* Following instruction in readme.md

## Console output
![Screenshot from 2020-05-18 18-20-04](https://user-images.githubusercontent.com/10920881/82196086-384ad980-9934-11ea-8c4e-7abe2af4571f.png)

**Comment by k0suke-murakami** [comment]
https://drive.google.com/file/d/1KZERZa2ZMHSdc9--nWu75bxspBS91BxW/view?usp=sharing

**Comment by LiJiangnanBit** [comment]
Hi, I think the program failed because the start state was not within the range of the reference points (red).
This could fail:
![2020-05-18 18-02-30屏幕截图.png](https://i.loli.net/2020/05/18/I9fAEnjmB7KdyQN.png)  
While this should work:
![2020-05-18 18-02-14屏幕截图.png](https://i.loli.net/2020/05/18/BZp1XAgKfChDwmR.png)    
The start position is mapped onto the smoothed reference path, which starts from the first red point you choose.   
![2020-05-18 18-09-32屏幕截图.png](https://i.loli.net/2020/05/18/VOKGvlYRa5Sg4JI.png)

**Comment by k0suke-murakami** [comment]
Thank you for the quick replay.

Still, trouble to get the result.
Here output with reference red points.
![Screenshot from 2020-05-18 19-22-17](https://user-images.githubusercontent.com/10920881/82202509-fa05e800-993c-11ea-8258-586ebe598f69.png)
![Screenshot from 2020-05-18 19-23-11](https://user-images.githubusercontent.com/10920881/82202560-0d18b800-993d-11ea-9b17-01ac1a99293b.png)

**Comment by k0suke-murakami** [comment]
Just let you know that it works when changing the smoothing method to `TensionSmoother`
![Screenshot from 2020-05-18 19-48-03](https://user-images.githubusercontent.com/10920881/82204831-91b90580-9940-11ea-9d13-37b61eb57d57.png)

![Screenshot from 2020-05-18 19-49-46](https://user-images.githubusercontent.com/10920881/82204991-ca58df00-9940-11ea-888c-4a422a5ca6d4.png)

**Comment by LiJiangnanBit** [comment]
I tried the input that you provided, but strangely, the failure didn't appear. :sweat_smile: 
![2020-05-18 20-35-57屏幕截图.png](https://i.loli.net/2020/05/18/uZvGNoaSJfAt8xy.png)    
So I can't say what's wrong with AngleDiffSmoother. But it will be abandoned soon because it's too slow to solve this non-linear program. And there's also a problem you may have observed in TensionSmoother: the result has minor trembling sometimes. It's very rare, but annoying. I'm developing a new smoothing method in another branch to replace AngleDiffSmoother and TensionSmoother.
